#!/usr/bin/env python3
"""
Convert a PromptedCRE LOI markdown draft into a professional .docx document.

Usage:
    python3 playbook/loi-to-docx.py working-deals/protech/properties/3203-s-sam-houston-pkwy/loi/loi-draft.md

Output:
    working-deals/protech/properties/3203-s-sam-houston-pkwy/loi/loi-draft.docx

The agent's LOI markdown has two sections:
  1. A YAML-like metadata header (Date, To, From, RE, body paragraphs)
  2. A terms table (markdown table or bold-label list)

This script converts that into a professional .docx matching standard
industrial tenant rep RFP/LOI conventions:
  - Cover letter page: date, recipient, RE line, body, signature, CC
  - Exhibit A page: two-column terms table (Term | Details)
  - Times New Roman, 1" margins, Table Grid style
"""

import re
import sys
from pathlib import Path

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT


def parse_loi_markdown(md_text: str) -> dict:
    """Parse the agent's markdown LOI into structured sections.

    Handles two formats:
      A) Metadata header with **Key:** Value lines + markdown table
      B) Traditional cover letter flow (date, recipient block, RE, body, signature)
    """
    loi = {
        "title": "",
        "date": "",
        "from_name": "",
        "to_name": "",
        "re_line": "",
        "cover_body": [],
        "signature_name": "",
        "signature_title": "",
        "signature_email": "",
        "signature_phone": "",
        "cc_lines": [],
        "terms": [],
    }

    lines = md_text.strip().split("\n")

    # --- Extract metadata from **Key:** Value lines ---
    metadata = {}
    body_lines = []
    in_terms_table = False
    past_metadata = False
    skip_sections = {"status", "drafted", "sent", "response"}

    for line in lines:
        stripped = line.strip()

        # Skip markdown artifacts
        if stripped.startswith("#"):
            loi["title"] = loi["title"] or stripped.lstrip("# ").strip()
            past_metadata = True
            continue
        if stripped == "---":
            continue
        if stripped.startswith("*Generated by") or stripped.startswith("*This Letter"):
            # Non-binding disclaimer — add to cover body
            cleaned = stripped.strip("*_")
            if "non-binding" in cleaned.lower():
                loi["cover_body"].append(cleaned)
            continue

        # Markdown table rows
        if stripped.startswith("|"):
            if re.match(r"\|[\s\-:|]+\|$", stripped):
                continue
            cells = [c.strip() for c in stripped.split("|")[1:-1]]
            if len(cells) >= 2:
                label = re.sub(r"\*\*", "", cells[0]).strip().rstrip(":")
                value = re.sub(r"\*\*", "", cells[1]).strip()
                # Skip header rows like "Term | Proposal"
                if label.lower() in ("term", "terms"):
                    in_terms_table = True
                    continue
                if label and not re.match(r"^-+$", label):
                    loi["terms"].append((label, value))
            continue

        # **Key:** Value metadata lines
        bold_match = re.match(r"\*\*(.+?)\*\*:?\s*(.*)", stripped)
        if bold_match:
            key = bold_match.group(1).rstrip(":").strip().lower()
            value = bold_match.group(2).strip()

            if key == "date":
                loi["date"] = value
            elif key in ("to", "recipient"):
                loi["to_name"] = value
            elif key in ("from", "sender", "tenant"):
                loi["from_name"] = value
            elif key in ("re", "subject", "property", "premises"):
                loi["re_line"] = value
            elif key in skip_sections:
                continue
            else:
                # Could be a standalone term
                loi["terms"].append((bold_match.group(1).rstrip(":").strip(), value))
            continue

        # Regular text lines (cover body candidates)
        if stripped and past_metadata:
            # Check if it's a status line
            if stripped.startswith("- **") and any(s in stripped.lower() for s in skip_sections):
                continue
            body_lines.append(stripped)

    # If we found body lines that aren't terms, add them to cover body
    for bl in body_lines:
        if not any(bl == t[1] for t in loi["terms"]):
            loi["cover_body"].append(bl)

    return loi


def build_docx(loi: dict, output_path: str):
    """Generate a formatted .docx LOI from parsed data."""
    doc = Document()

    # --- Page setup ---
    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)

    # --- Default font ---
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Times New Roman"
    font.size = Pt(11)
    font.color.rgb = RGBColor(0, 0, 0)

    # === COVER LETTER PAGE ===

    # Date
    if loi["date"]:
        p = doc.add_paragraph(loi["date"])
        p.space_after = Pt(12)

    # Recipient
    if loi["to_name"]:
        p = doc.add_paragraph(loi["to_name"])
        p.space_after = Pt(12)

    # RE line
    re_text = loi["re_line"]
    if not re_text and loi["title"]:
        re_text = loi["title"]
    if re_text:
        p = doc.add_paragraph()
        run = p.add_run(f"RE: {re_text}" if not re_text.upper().startswith("RE") else re_text)
        run.bold = True
        p.space_after = Pt(12)

    # Salutation
    if loi["to_name"]:
        # Extract a last name for salutation
        name_parts = loi["to_name"].split()
        # If it starts with a company reference like "National Property Holdings (via...)"
        if "(" in loi["to_name"]:
            # Use the part in parens if it has a person name
            paren = re.search(r"\((?:via\s+)?(.+?)\)", loi["to_name"])
            if paren:
                salutation = f"Dear {paren.group(1).split('—')[0].split('/')[0].strip()},"
            else:
                salutation = "Dear Sir or Madam,"
        else:
            salutation = f"Dear {name_parts[0]},"
        p = doc.add_paragraph(salutation)
        p.space_after = Pt(6)

    # Standard RFP intro paragraph
    tenant_name = loi["from_name"] or "[Tenant]"
    premises = loi["re_line"] or "[Premises]"
    intro = (
        f"We are pleased to present you with the following Request for Proposal "
        f'("RFP") on behalf of {tenant_name} ("Tenant") for a new lease at '
        f"the above referenced premises. Please review and respond to the "
        f"information provided below."
    )
    p = doc.add_paragraph(intro)
    p.space_after = Pt(6)

    # Non-binding disclaimer
    disclaimer_found = False
    for body_text in loi["cover_body"]:
        if "non-binding" in body_text.lower():
            p = doc.add_paragraph(body_text)
            p.space_after = Pt(6)
            disclaimer_found = True

    if not disclaimer_found:
        p = doc.add_paragraph(
            "The above Request for Proposal reflects the current interest of the "
            "Tenant to Lease the Premises. It is specifically understood and agreed "
            "that no legal rights or obligations exist between either party until "
            "and only if a Lease document is executed."
        )
        p.space_after = Pt(6)

    # Response request
    p = doc.add_paragraph(
        "Please notify us of your response to this RFP at your earliest "
        "convenience, and do not hesitate to contact me via phone or email."
    )
    p.space_after = Pt(12)

    # Sincerely
    p = doc.add_paragraph("Sincerely,")
    p.space_before = Pt(6)
    p.space_after = Pt(24)

    # Signature block
    p = doc.add_paragraph()
    if loi["signature_name"]:
        run = p.add_run(loi["signature_name"])
        run.bold = True
    if loi["signature_title"]:
        p.add_run(f"\n{loi['signature_title']}")
    if loi["signature_email"]:
        p.add_run(f"\n{loi['signature_email']}")
    if loi["signature_phone"]:
        p.add_run(f"\n{loi['signature_phone']}")

    # Placeholder for user to fill in their signature
    if not loi["signature_name"]:
        p = doc.add_paragraph()
        run = p.add_run("[Your Name]")
        run.bold = True
        p.add_run("\n[Your Title]")
        p.add_run("\n[Your Email]")
        p.add_run("\n[Your Phone]")

    # CC
    if loi["cc_lines"]:
        p = doc.add_paragraph()
        p.space_before = Pt(12)
        run = p.add_run("CC:")
        run.bold = True
        for cc in loi["cc_lines"]:
            p.add_run(f"\n{cc}")

    # === EXHIBIT A PAGE ===
    doc.add_page_break()

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run("EXHIBIT 'A'")
    run.bold = True
    run.font.size = Pt(14)
    p.space_after = Pt(6)

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run("Terms and Conditions")
    run.bold = True
    run.font.size = Pt(12)
    p.space_after = Pt(12)

    # Terms table
    if loi["terms"]:
        table = doc.add_table(rows=len(loi["terms"]), cols=2)
        table.style = "Table Grid"
        table.alignment = WD_TABLE_ALIGNMENT.CENTER

        for row in table.rows:
            row.cells[0].width = Inches(2)
            row.cells[1].width = Inches(4.5)

        for idx, (label, value) in enumerate(loi["terms"]):
            # Label cell
            cell_label = table.rows[idx].cells[0]
            cell_label.text = ""
            p = cell_label.paragraphs[0]
            run = p.add_run(f"{label}:")
            run.bold = True
            run.font.name = "Times New Roman"
            run.font.size = Pt(10)

            # Value cell
            cell_value = table.rows[idx].cells[1]
            cell_value.text = ""
            p = cell_value.paragraphs[0]
            run = p.add_run(value)
            run.font.name = "Times New Roman"
            run.font.size = Pt(10)

    # Save
    doc.save(output_path)
    return output_path


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 playbook/loi-to-docx.py <path-to-loi-draft.md>")
        print("       Output .docx will be saved next to the .md file.")
        sys.exit(1)

    md_path = Path(sys.argv[1])
    if not md_path.exists():
        print(f"Error: {md_path} not found")
        sys.exit(1)

    md_text = md_path.read_text()
    loi = parse_loi_markdown(md_text)

    output_path = md_path.with_suffix(".docx")
    build_docx(loi, str(output_path))
    print(f"Created: {output_path}")


if __name__ == "__main__":
    main()
